### ISSUE TITLE
Is it possible to compute a hash function (md5Hash) inside security rules?

### ISSUE THREAD

**Issue by botmane** [firebase/bolt#221]
Hello,

I would like to create a custom security rule where I check if md5Hash(auth.uid) === "foo". Is there any way to do it using bolt?

Thanks,

**Comment by rockwotj** [comment]
Currently, we don't expose any hash functions in rules, please file a feature request [here](https://firebase.google.com/support/contact/bugs-features/) if you have a use case for this.

**Comment by rockwotj** [comment]
This isn't really related to bolt, but just whatever functions are available in Firebase Database Rules, so I'm going to close this out (but we got your feature request, so thanks!)

**Comment by justi-n** [comment]
@rockwotj I kind of have a use case for the same. Is there a link where I can check the current status of this feature request?

**Comment by rockwotj** [comment]
Sadly, we don't have a public issue tracker or anything available for you to track @justi-n

**Comment by mikelehen** [comment]
@botmane @justi-n Can you explain what your use cases are?

**Comment by scottcrossen** [comment]
Hi! `hashing.md5(request.auth.uid.toUtf8()).toBase64() == "foo"` is what you want.

**Comment by rockwotj** [comment]
Note this works in Firestore and Storage security rules, not Realtime Database Rules

**Comment by ethanyu94** [comment]
Hi @scottcrossen! I'm having trouble getting correct hash values. Posted a question earlier here: https://stackoverflow.com/questions/61565409/firebase-security-hashing-uid-doesnt-match-client-computed. Basically the result of `hashing.md5(request.auth.uid.toUtf8()).toBase64()` don't match what I'm computing in other libraries. Any thoughts?

**Comment by anubhavkamath** [comment]
This is great. Any possibility this can be extended to a keyed hash (HMAC-SHA*) or something like that? I have a use case where I need to do a one way keyed hash on a random string. The use case is this. A user creates a firestore document. The user's uid is stored in an adminId field of the document. So the database rules restrict write access to only the user with the uid = adminId. Now I have a case where the admin has to grant write access to an anonymous login user to this (and only this document). My thought was that the admin would generate a keyed one-way hash using a secret string and write the key to the document along with the hash to the secret string. The secret string would be distributed securely (between the two parties) to the user who will be granted write access. The user logs in anonymously and reads the key from the document (along with other contents as the document can be read). In order to make changes to the document, there will be another field to enter the secret string. If entered correctly when the user attempts to make changes, the security rules will determine that the uid of the user does not match the adminId, so it will check the secret string field and compute the hash using the key in the document. If the hash matches the hash also in the document, the document write succeeds. Please let me know if there's a way this could be implemented within the security rules or if there's another way to do this? I assume since you have md5 already adding an HMAC-md5 with a key parameter wouldn't be that big a stretch?

**Comment by jangruenwaldt** [comment]
An example that works:     

Rule:
```
match /doc/{userID} {
        allow read, write: if hashing.md5(request.auth.uid.toUtf8()).toHexString() == userID;
}
```

Dart: (similar in your programming language of choice)
```
 String hashUid(String uid) => md5
      .convert(uid)
      .toString()
      .toUpperCase();

```
