### ISSUE TITLE
Inconsistent function using root

### ISSUE THREAD

**Issue by aj0strow** [firebase/bolt#87]
Hey, first time trying bolt and some weird stuff happened. 

Here's the input:

```
// Functions

isAdmin() = root.admin[auth.uid] != null;

// Paths

path / {
  read() = false;
  write() = false;
}

path /admin {
  read() = true;
}

path /accounts {
  read() = isAdmin();
  write() = isAdmin();
}
```

Here's the output:

```json
{
  "rules": {
    "admin": {
      ".read": "true"
    },
    "accounts": {
      ".read": "root.child('admin').child(auth.uid).val() != null",
      ".write": "newData.parent().child('admin').child(auth.uid).val() != null"
    }
  }
}
```

It looks like `isAdmin()` means one thing for accounts `read()`, and something different for accounts `write()`. Is `root` a context-sensitive keyword? 

Also how come the root level instructions didn't make it in? To my understanding firebase implicitly allows reads and writes unless you explicitly disallow root. Is that true? If it is true, is there some way to reference the root path besides `path /` like how i tried?

**Comment by mckoss** [comment]
I think everything here is by design.  I can explain.

To support [multi-location updates](https://www.firebase.com/blog/2015-09-24-atomic-writes-and-more.html), Bolt uses newData and relative path references rather than descend from root.  You can override this behavior by using prior(root) in your function instead.

Firebase does not implicitly allow reads and writes (though the default rule is read() = true, write() =true).  Any read write rule that evaluates to false is basically a no-op (just as validate rules that are true are also eliminated as having no effect).

**Comment by aj0strow** [comment]
@mckoss ok that makes sense for root rules. 

I still don't understand `root` being changed to `newData`. I must be missing something obvious?

**Comment by mckoss** [comment]
The reason is subtle (not obvious):  To support multi-location updates, you need to be able to write rules that will refer to the "new" value of the date.  The standard in Bolt is that in write and validation rules, `this` and `root` references are newData values (in read rules, this and root are `data` - old/existing - values).

Ideally, we would have a `newRoot` variable in JSON rules - so we could transform `root` to `newRoot` in those cases.  Since we don't (yet), Bolt generates the equivalent rules using newData.parent().... (i.e. a relative reference to the newData).

If you are not using multi-location updates, and you want Bolt to generate a simpler rule, you can use `prior(root)` instead of `root`.

**Comment by aj0strow** [comment]
Oh ok, gotchu. That's kinda cool actually!
