### ISSUE TITLE
`!= null` does not render as `.exists()`

### ISSUE THREAD

**Issue by kayoub5** [firebase/bolt#94]
based on https://github.com/firebase/bolt/blob/master/docs/language.md#ruledatasnapshot-methods 
For function
`repoHasUser(repo, user) = prior(root).repos[repo].users[user] != null;`
expected output
`root.child('jobs').child($repo).child($job).exists()`
actual output
`root.child('jobs').child($repo).child($job).val() != null`
Am I missing something?

**Comment by mckoss** [comment]
For economy, Bolt does not have the exists() method on references - since it is identical to ref != null.  In the JSON language, these two statements are also equivalent:

ref.exists() === ref.val() != null

Bolt outputs the != null test in JSON (though it could have used the exists() method instead).  Both work exactly the same.

**Comment by zoechi** [comment]
That doesn't seem to be true for `!ref.exists()`
`ref.val() == null` doesn't seem to work.
