### ISSUE TITLE
Should redeclaration of properties in an extended type override instead of add-to?

### ISSUE THREAD

**Issue by brianneisler** [firebase/bolt#96]
Currently, if I want to change the type of a property that is declared in some parent type I have to completely redeclare all properties for my child type and not extend the base type.

Example of what I'd like to be able to do...
```
// Want to change id to a type that does not match the Id regex
type Child extends Entity {
  id: ChildId
}

type ChildId extends String {
  validate() = isChildId(this);
}

function isChildId(value) {
  return value.test(/some other regex/);
}

type Entity {
  createdAt: Number,
  id: Id,
  updatedAt: Number
}

type Id extends String {
  validate() = isId(this);
}

function isId(value) {
  return value.test(/^-[a-zA-Z0-9_]+$/);
}
```
However, the above code outputs the id for Child to...
```json
 "id": {
          ".validate": "newData.isString() && newData.val().matches(/^-[a-zA-Z0-9_]+$/) && newData.isString() && newData.val().matches(/some other regex/)"
 }
```
Which isn't useful since the id value can't match both regex tests.

**Comment by mckoss** [comment]
The convention in Bolt for type extension, is you can add additional constraints, but you can't relax them; so all constraints of the parent type must be true as well as constraints of the child.  The way to accomplish what you want would be to derive both Entity and Child from a common base type that does not include the id field.

I was considering that it might be more useful to get a compiler warning when you override a property (especially in the case where the type information is obviously conflicting and can never validate to true).

**Comment by scriby** [comment]
I ran into a case today where overriding was what I wanted it to, but addition worked as well. The rendered expression ended up repeating some logic (for instance, it was checking isString() and the same length constraint multiple times).

**Comment by brianneisler** [comment]
@scriby ran in to the same thing here. Finding lots of repeat logic due to everything being additive.

**Comment by mckoss** [comment]
You should be able to factor common parts of rules into a "sub-type" and then inherit from that type.  Generic types also give you a very powerful way to express general patterns, but leave out the specific typing until you assign the type at a specific path location.

What is not supported (by design), is relaxing or changing some elements of a parent type, while restricting other elements.  If you have examples of where you find you have to repeat yourself in your type definitions, you can post them here, and I'd be happy to take a stab at how I'd define them by taking advantage of the composition features of Bolt.

**Comment by mckoss** [comment]
(Side note: expression simplification is something I've been working on - for those cases where you do get repetition in the final JSON expressions that can be refactored and simplified).

**Comment by htkm** [comment]
@mckoss, do you have any updates on "expression simplification"? Thank you.
